/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.CargaDao;
import br.com.bomtransporte.dao.PedidoDao;
import br.com.bomtransporte.dao.VeiculoDao;
import br.com.bomtransporte.modelo.Carga;
import br.com.bomtransporte.modelo.ModeloTabela;
import br.com.bomtransporte.modelo.Veiculo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Gustavo Carvalho <gustavo.carvalho.costa@outlook.com>
 */
public class FormVeiculoCargas extends javax.swing.JFrame {

    /**
     * Creates new form FormVeiculoCargas
     */
    private CargaDao cargaDao;
    private Carga cargaSelecionada;
    public static Integer idVeiculoSelecionado;

    public FormVeiculoCargas() {
        initComponents();
        preencherTabelaVeiculoCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void preencherTabelaVeiculoCarga() {

        ArrayList dados = new ArrayList();
        cargaDao = new CargaDao();
        Carga carga = new Carga();
        String[] colunas = new String[]{"ID", "DESCRICAO", "STATUS"};

        try {
            final List<Object> listaCarga = cargaDao.listarCargasDoVeiculo(idVeiculoSelecionado);

            if (listaCarga != null && listaCarga.size() > 0) {
                for (Object cargaAtual : listaCarga) {
                    carga = (Carga) cargaAtual;
                    dados.add(new Object[]{carga.getIdCarga(), carga.getDescricao(), carga.getStatus()});
                }
            }

            ModeloTabela modTabela = new ModeloTabela(dados, colunas);
            jTB_VeiculoCarga.setModel(modTabela);
            jTB_VeiculoCarga.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTB_VeiculoCarga.getColumnModel().getColumn(0).setResizable(false);
            jTB_VeiculoCarga.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTB_VeiculoCarga.getColumnModel().getColumn(1).setResizable(false);
            jTB_VeiculoCarga.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTB_VeiculoCarga.getColumnModel().getColumn(2).setResizable(false);

            jTB_VeiculoCarga.getTableHeader().setReorderingAllowed(false);
            jTB_VeiculoCarga.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTB_VeiculoCarga.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            jTB_VeiculoCarga.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        List<Object> lista = cargaDao.listarCargasDoVeiculo(idVeiculoSelecionado);
                        cargaSelecionada = (Carga) lista.
                                get(jTB_VeiculoCarga.convertRowIndexToModel(jTB_VeiculoCarga.getSelectedRow()));

                        //     if (veiculoDao.listarVeiculosAtivos().size() > 0 && veiculoDao.listarVeiculosAtivos() != null) {}
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(FormVeiculoCargas.this, "Erro genérico1: " + ex.getMessage());
                        ex.printStackTrace(System.err);
                    }
                }

            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro genérico2: " + e.getMessage());
            e.printStackTrace();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBT_CargaExtraviada = new javax.swing.JButton();
        jBT_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTB_VeiculoCarga = new javax.swing.JTable();
        jBT_CasaFechada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBT_CargaExtraviada.setBackground(new java.awt.Color(0, 0, 0));
        jBT_CargaExtraviada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_CargaExtraviada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/alterar-icon.png"))); // NOI18N
        jBT_CargaExtraviada.setText("carga extraviada");
        jBT_CargaExtraviada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_CargaExtraviadaActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_CargaExtraviada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 220, 60));

        jBT_Voltar.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/retornar-icon.png"))); // NOI18N
        jBT_Voltar.setText("Voltar");
        jBT_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, 60));

        jTB_VeiculoCarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTB_VeiculoCarga);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 210));

        jBT_CasaFechada.setBackground(new java.awt.Color(0, 0, 0));
        jBT_CasaFechada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_CasaFechada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/alterar-icon.png"))); // NOI18N
        jBT_CasaFechada.setText("Casa fechada");
        jBT_CasaFechada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_CasaFechadaActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_CasaFechada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_CargaExtraviadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_CargaExtraviadaActionPerformed
        //verifica se o status da carga e nulo
        if (cargaSelecionada.getStatus() == null || cargaSelecionada.getStatus().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao acessar o veiculo!\n O status do veiculo esta em branco.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int result = JOptionPane.showConfirmDialog(this,
                "Tem certeza que esta carga foi extraviada?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            cargaDao = new CargaDao();
            try {
                cargaDao.updateStatusDaCarga("Carga extraviada", cargaSelecionada.getIdCarga());
                cargaDao.updateIdVeiculo(cargaSelecionada.getIdCarga());
                preencherTabelaVeiculoCarga();
            } catch (Exception ex) {
                Logger.getLogger(FormVeiculoCargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        preencherTabelaVeiculoCarga();
    }//GEN-LAST:event_jBT_CargaExtraviadaActionPerformed

    private void jBT_CasaFechadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_CasaFechadaActionPerformed
        //verifica se o status da carga e nulo
        if (cargaSelecionada.getStatus() == null || cargaSelecionada.getStatus().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao acessar o veiculo!\n O status do veiculo esta em branco.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int result = JOptionPane.showConfirmDialog(this,
                "Tem certeza que esta carga nao foi entregue?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            cargaDao = new CargaDao();
            try {
                cargaDao.updateStatusDaCarga("Aguardando", cargaSelecionada.getIdCarga());
                cargaDao.updateIdVeiculo(cargaSelecionada.getIdCarga());
                preencherTabelaVeiculoCarga();
            } catch (Exception ex) {
                Logger.getLogger(FormVeiculoCargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        preencherTabelaVeiculoCarga();
    }//GEN-LAST:event_jBT_CasaFechadaActionPerformed

    private void jBT_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_VoltarActionPerformed
        int result = JOptionPane.showConfirmDialog(this,
                "As outras cargas foram entregues corretamente?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {

            try {
                final List<Object> listaCarga = cargaDao.listarCargasDoVeiculo(idVeiculoSelecionado);
                cargaDao = new CargaDao();

                if (listaCarga != null && listaCarga.size() > 0) {

                    for (Object cargaAtual : listaCarga) {
                        Carga carga = (Carga) cargaAtual;

                        if (carga.getStatus().equals("Saiu para entrega")) {
                            cargaDao.updateStatusDaCarga("Entregue", carga.getIdCarga());
                        }
                    }

                    final List<Object> listaCargaAguardando = cargaDao.listarCargasPorStatus(cargaSelecionada.getIdPedido_Cli(), "Aguardando");
                    if (listaCargaAguardando == null || listaCargaAguardando.size() < 1) {

                        final List<Object> listaCargaSaiuParaEntrega = cargaDao.listarCargasPorStatus(cargaSelecionada.getIdPedido_Cli(), "Saiu para entrega");
                        if (listaCargaAguardando == null || listaCargaAguardando.size() < 1) {
                            PedidoDao pedidoDao = new PedidoDao();
                            pedidoDao.update(cargaSelecionada.getIdPedido_Cli(), "Entregue");
                        }

                    }
                    JOptionPane.showMessageDialog(this, "Todas as cargas foram entregues com sucesso!");
                }

            } catch (Exception ex) {
                Logger.getLogger(FormVeiculoCargas.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
            VeiculoDao veiculoDao = new VeiculoDao();
            try {
                veiculoDao.updateStatus("Aguardando", idVeiculoSelecionado);
            } catch (Exception ex) {
                Logger.getLogger(FormVeiculoCargas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        dispose();
        
        
    }//GEN-LAST:event_jBT_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVeiculoCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVeiculoCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVeiculoCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVeiculoCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVeiculoCargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_CargaExtraviada;
    private javax.swing.JButton jBT_CasaFechada;
    private javax.swing.JButton jBT_Voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTB_VeiculoCarga;
    // End of variables declaration//GEN-END:variables
}
