package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.CargaDao;
import br.com.bomtransporte.modelo.Carga;
import br.com.bomtransporte.modelo.ModeloTabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author JhonattanSouza_
 */
public class FormVisualizarCargas extends javax.swing.JFrame {
    private CargaDao cargaDao;
    /**
     * Creates new form FormVisualizarCargas
     */
    public FormVisualizarCargas() {
        initComponents();
        preencherTabela();
    }
    
     private void preencherTabela() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "DESCRICAO", "QTD", "DIMENSÃO", "STATUS"};
        try {
            cargaDao = new CargaDao();
            List<Object> lista = cargaDao.listarCargas(FormPedidos.idPedido);
            if (lista != null && lista.size() > 0) {
                for (Object cargaAtual : lista) {
                    Carga carga = (Carga) cargaAtual;
                    dados.add(new Object[]{carga.getIdCarga(), carga.getDescricao(), carga.getQuantidade(), carga.getDimensaoCubica(), carga.getStatus()});
                }
            }

            ModeloTabela modTabela = new ModeloTabela(dados, colunas);
            jTB_Cargas.setModel(modTabela);
            jTB_Cargas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTB_Cargas.getColumnModel().getColumn(0).setResizable(false);
            jTB_Cargas.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTB_Cargas.getColumnModel().getColumn(1).setResizable(false);
            jTB_Cargas.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTB_Cargas.getColumnModel().getColumn(2).setResizable(false);
            jTB_Cargas.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTB_Cargas.getColumnModel().getColumn(3).setResizable(false);
            jTB_Cargas.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTB_Cargas.getColumnModel().getColumn(4).setResizable(false);

            jTB_Cargas.getTableHeader().setReorderingAllowed(false);
            jTB_Cargas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTB_Cargas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//            jTB_Cargas.addMouseListener(new MouseAdapter() {
//                @Override
//                public void mouseClicked(MouseEvent e) {
//   
//                }
//            });
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO INESPERADO. POR FAVOR CONTATE O ADMINISTRADOR DO SISTEMA.\n",
                    "ERRO INESPERADO.",JOptionPane.INFORMATION_MESSAGE);
            e.printStackTrace(System.err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPN_Background = new javax.swing.JPanel();
        jSP_Tabela = new javax.swing.JScrollPane();
        jTB_Cargas = new javax.swing.JTable();
        jLB_Fechar5 = new javax.swing.JLabel();
        jLB_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPN_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTB_Cargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSP_Tabela.setViewportView(jTB_Cargas);

        jPN_Background.add(jSP_Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 240));

        jLB_Fechar5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLB_Fechar5.setForeground(new java.awt.Color(255, 255, 255));
        jLB_Fechar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Fechar5.setText("X");
        jLB_Fechar5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLB_Fechar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLB_Fechar5MouseReleased(evt);
            }
        });
        jPN_Background.add(jLB_Fechar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        jLB_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/cep-bg.png"))); // NOI18N
        jPN_Background.add(jLB_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        getContentPane().add(jPN_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLB_Fechar5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLB_Fechar5MouseReleased
        dispose();
    }//GEN-LAST:event_jLB_Fechar5MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormVisualizarCargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLB_Background;
    private javax.swing.JLabel jLB_Fechar4;
    private javax.swing.JLabel jLB_Fechar5;
    private javax.swing.JPanel jPN_Background;
    private javax.swing.JScrollPane jSP_Tabela;
    private javax.swing.JTable jTB_Cargas;
    // End of variables declaration//GEN-END:variables
}
