package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.FuncionarioDao;
import br.com.bomtransporte.modelo.Funcionario;
import br.com.bomtransporte.regrasnegocio.FuncionarioRN;
import br.com.bomtransporte.util.ValidarEmail;
import javax.swing.JOptionPane;

/**
 *
 * @author JhonattanSouza_
 */
public class FormRecuperarSenha extends javax.swing.JFrame {

    /**
     * Creates new form FormRecuperarSenha
     */
    public FormRecuperarSenha() {
        initComponents();
        jLB_Mensagem.setVisible(false);
    }

    private void exibirMensagem(javax.swing.JLabel label, String mensagem) {
        label.setVisible(true);
        label.setText(mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTF_Email = new javax.swing.JTextField();
        jBT_AlterarSenha = new javax.swing.JButton();
        jLB_Mensagem = new javax.swing.JLabel();
        jLB_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTF_Email.setBorder(null);
        jTF_Email.setOpaque(false);
        getContentPane().add(jTF_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 250, 30));

        jBT_AlterarSenha.setBorder(null);
        jBT_AlterarSenha.setContentAreaFilled(false);
        jBT_AlterarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_AlterarSenha.setFocusPainted(false);
        jBT_AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_AlterarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_AlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 340, 40));

        jLB_Mensagem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLB_Mensagem.setForeground(new java.awt.Color(204, 0, 0));
        jLB_Mensagem.setText("ERROR_PLACEHOLDER");
        getContentPane().add(jLB_Mensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, -1));

        jLB_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/esqueci-senha-form.png"))); // NOI18N
        getContentPane().add(jLB_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_AlterarSenhaActionPerformed
        try {
            String email = jTF_Email.getText().trim();
            ValidarEmail ve = new ValidarEmail();
            if (ve.validar(email.trim())) {
                FuncionarioDao funcionarioDao = new FuncionarioDao();
                Funcionario funcionario = funcionarioDao.consultarEmail(email);
                if (funcionario != null) {
                    FuncionarioRN funcionarioRN = new FuncionarioRN();
                    String novaSenha = funcionarioRN.gerarSenha(funcionario);
                    funcionarioDao.alterarSenha(funcionario, FuncionarioRN.criptografarMd5(novaSenha), true);
                    funcionarioRN.enviarEmail(email, funcionario.getCargo(), novaSenha);
                    JOptionPane.showMessageDialog(this, "E-mail com nova senha enviado com sucesso!");
                    dispose();
                } else {
                    exibirMensagem(jLB_Mensagem, "E-mail não encontrado.");
                }
            } else {
                exibirMensagem(jLB_Mensagem, "Email inválido.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado, por favor tente novamente. " + e.getMessage());
        }
    }//GEN-LAST:event_jBT_AlterarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormRecuperarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_AlterarSenha;
    private javax.swing.JLabel jLB_Background;
    private javax.swing.JLabel jLB_Mensagem;
    private javax.swing.JTextField jTF_Email;
    // End of variables declaration//GEN-END:variables
}
