package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.VeiculoDao;
import br.com.bomtransporte.modelo.FuncionarioSingleton;
import br.com.bomtransporte.util.Tela;
import javax.swing.JOptionPane;

/**
 *
 * @author JhonattanSouza_
 */
public class FormDashAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormDashAdmin
     */
    public FormDashAdmin() {
        initComponents();
        jLB_Nome.setText(FuncionarioSingleton.getFuncionario().getNome());
        Tela.adicionarHover(jBT_Clientes, jBT_Funcionarios, jBT_Pedidos, jBT_PesqCli, jBT_Relatorios, jBT_Rotas, jBT_Senha, jBT_Volumes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPN_Background = new javax.swing.JPanel();
        jLB_Legenda = new javax.swing.JLabel();
        jLB_Legenda1 = new javax.swing.JLabel();
        jLB_Legenda2 = new javax.swing.JLabel();
        jLB_Legenda3 = new javax.swing.JLabel();
        jLB_Legenda4 = new javax.swing.JLabel();
        jLB_Legenda5 = new javax.swing.JLabel();
        jLB_Legenda6 = new javax.swing.JLabel();
        jLB_Legenda7 = new javax.swing.JLabel();
        jLB_Icon = new javax.swing.JLabel();
        jLB_Icon1 = new javax.swing.JLabel();
        jLB_Icon2 = new javax.swing.JLabel();
        jLB_Icon3 = new javax.swing.JLabel();
        jLB_Icon4 = new javax.swing.JLabel();
        jLB_Icon5 = new javax.swing.JLabel();
        jLB_Icon6 = new javax.swing.JLabel();
        jLB_Icon7 = new javax.swing.JLabel();
        jBT_Funcionarios = new javax.swing.JLabel();
        jBT_Clientes = new javax.swing.JLabel();
        jBT_Senha = new javax.swing.JLabel();
        jBT_Relatorios = new javax.swing.JLabel();
        jBT_Pedidos = new javax.swing.JLabel();
        jBT_Volumes = new javax.swing.JLabel();
        jBT_PesqCli = new javax.swing.JLabel();
        jBT_Rotas = new javax.swing.JLabel();
        jLB_Nome = new javax.swing.JLabel();
        jLB_BemVindo = new javax.swing.JLabel();
        jBT_Sair = new javax.swing.JButton();
        jBT_Logout = new javax.swing.JButton();
        jLB_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPN_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLB_Legenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda.setText("<html>Administrar<br/>Funcionários</html>");
        jLB_Legenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, 60));

        jLB_Legenda1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda1.setText("<html>Cadastrar<br/>Clientes</html>");
        jLB_Legenda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, 60));

        jLB_Legenda2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda2.setText("<html>Alterar<br/>Senha</html>");
        jLB_Legenda2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 150, 60));

        jLB_Legenda3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda3.setText("<html>Gerar<br/>Relatórios</html>");
        jLB_Legenda3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 150, 60));

        jLB_Legenda4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda4.setText("<html>Enviar<br/>Pedidos</html>");
        jLB_Legenda4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 150, 60));

        jLB_Legenda5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda5.setText("<html>Gerenciar<br/>Peso/Volumes</html>");
        jLB_Legenda5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 150, 60));

        jLB_Legenda6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda6.setText("<html>Pesquisar Clientes<br/>Cadastrar Pedidos</html>");
        jLB_Legenda6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 150, 60));

        jLB_Legenda7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda7.setText("<html>Administrar<br/>Rotas e Valores</html>");
        jLB_Legenda7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 150, 60));

        jLB_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/funcionario-icon.png"))); // NOI18N
        jLB_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 60));

        jLB_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/cliente-icon.png"))); // NOI18N
        jLB_Icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, 60));

        jLB_Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/senha-icon.png"))); // NOI18N
        jLB_Icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 50, 60));

        jLB_Icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/relat-icon.png"))); // NOI18N
        jLB_Icon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 50, 60));

        jLB_Icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/caminhao-icon.png"))); // NOI18N
        jLB_Icon4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, 60));

        jLB_Icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/peso-icon.png"))); // NOI18N
        jLB_Icon5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 50, 60));

        jLB_Icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/pesquisar-icon.png"))); // NOI18N
        jLB_Icon6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 50, 60));

        jLB_Icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/money-icon.png"))); // NOI18N
        jLB_Icon7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 50, 60));

        jBT_Funcionarios.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Funcionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Funcionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_FuncionariosMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Funcionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 150));

        jBT_Clientes.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_ClientesMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 150));

        jBT_Senha.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Senha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_SenhaMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 150, 150));

        jBT_Relatorios.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Relatorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_RelatoriosMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 150, 150));

        jBT_Pedidos.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Pedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Pedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_PedidosMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 150));

        jBT_Volumes.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Volumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Volumes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Volumes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Volumes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_VolumesMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Volumes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, 150));

        jBT_PesqCli.setBackground(new java.awt.Color(0, 0, 0));
        jBT_PesqCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_PesqCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_PesqCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_PesqCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_PesqCliMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_PesqCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 150, 150));

        jBT_Rotas.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Rotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Rotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Rotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Rotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_RotasMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Rotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 150, 150));

        jLB_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Nome.setText("NAME_PLACEHOLDER");
        jPN_Background.add(jLB_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 530, 40));

        jLB_BemVindo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_BemVindo.setText("Bem-Vindo(a)");
        jPN_Background.add(jLB_BemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, 40));

        jBT_Sair.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/sair-icon.png"))); // NOI18N
        jBT_Sair.setText("Sair do Sistema");
        jBT_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_SairActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 180, -1));

        jBT_Logout.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/logout-icon.png"))); // NOI18N
        jBT_Logout.setText("Logout");
        jBT_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_LogoutActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 130, -1));

        jLB_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/menu-principal-background.png"))); // NOI18N
        jPN_Background.add(jLB_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPN_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBT_SairActionPerformed

    private void jBT_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_LogoutActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_LogoutActionPerformed

    private void jBT_FuncionariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_FuncionariosMouseReleased
        FormCadastrarFuncionario formFuncionario = new FormCadastrarFuncionario();
        formFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_FuncionariosMouseReleased

    private void jBT_ClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_ClientesMouseReleased
        FormCadastrarCliente formCliente = new FormCadastrarCliente();
        formCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_ClientesMouseReleased

    private void jBT_SenhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_SenhaMouseReleased
        FormAlterarSenha formSenha = new FormAlterarSenha();
        formSenha.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_SenhaMouseReleased

    private void jBT_RelatoriosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_RelatoriosMouseReleased
        FormDashboardRelat formDash = new FormDashboardRelat();
        formDash.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_RelatoriosMouseReleased

    private void jBT_PedidosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_PedidosMouseReleased

        FormPedidos formPedidos = new FormPedidos();
        formPedidos.setVisible(true);
        dispose();

//        VeiculoDao vDao = new VeiculoDao();
//        try {
//            if (vDao.listarVeiculosAtivos() == null || vDao.listarVeiculosAtivos().size() <= 0) {
//                JOptionPane.showMessageDialog(this, "TODOS OS VEÍCULOS EM ROTA. NÃO É POSSÍVEL ENVIAR NOVOS PEDIDOS PARA ENTREGA.\n"
//                        + "AGUARDE UM VEÍCULO RETORNAR E TENTE NOVAMENTE", "VEÍCULO EM ROTA", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                FormPedidos formPedidos = new FormPedidos();
//                formPedidos.setVisible(true);
//                dispose();
//            }
//        } catch (Exception ex) {
//
//        }

    }//GEN-LAST:event_jBT_PedidosMouseReleased

    private void jBT_VolumesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_VolumesMouseReleased
        FormManterPeso formPeso = new FormManterPeso();
        formPeso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_VolumesMouseReleased

    private void jBT_PesqCliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_PesqCliMouseReleased
        FormClientePedido formCliente = new FormClientePedido();
        formCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_PesqCliMouseReleased

    private void jBT_RotasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_RotasMouseReleased
        FormCadastrarRota fcr = new FormCadastrarRota();
        fcr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_RotasMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormDashAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBT_Clientes;
    private javax.swing.JLabel jBT_Funcionarios;
    private javax.swing.JButton jBT_Logout;
    private javax.swing.JLabel jBT_Pedidos;
    private javax.swing.JLabel jBT_PesqCli;
    private javax.swing.JLabel jBT_Relatorios;
    private javax.swing.JLabel jBT_Rotas;
    private javax.swing.JButton jBT_Sair;
    private javax.swing.JLabel jBT_Senha;
    private javax.swing.JLabel jBT_Volumes;
    private javax.swing.JLabel jLB_Background;
    private javax.swing.JLabel jLB_BemVindo;
    private javax.swing.JLabel jLB_Icon;
    private javax.swing.JLabel jLB_Icon1;
    private javax.swing.JLabel jLB_Icon2;
    private javax.swing.JLabel jLB_Icon3;
    private javax.swing.JLabel jLB_Icon4;
    private javax.swing.JLabel jLB_Icon5;
    private javax.swing.JLabel jLB_Icon6;
    private javax.swing.JLabel jLB_Icon7;
    private javax.swing.JLabel jLB_Legenda;
    private javax.swing.JLabel jLB_Legenda1;
    private javax.swing.JLabel jLB_Legenda2;
    private javax.swing.JLabel jLB_Legenda3;
    private javax.swing.JLabel jLB_Legenda4;
    private javax.swing.JLabel jLB_Legenda5;
    private javax.swing.JLabel jLB_Legenda6;
    private javax.swing.JLabel jLB_Legenda7;
    private javax.swing.JLabel jLB_Nome;
    private javax.swing.JPanel jPN_Background;
    // End of variables declaration//GEN-END:variables
}
