package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.CargaDao;
import br.com.bomtransporte.dao.PedidoDao;
import br.com.bomtransporte.dao.VeiculoDao;
import static br.com.bomtransporte.formulario.FormVeiculoCargas.idVeiculoSelecionado;
import br.com.bomtransporte.modelo.Carga;
import br.com.bomtransporte.modelo.Funcionario;
import br.com.bomtransporte.modelo.FuncionarioSingleton;
import br.com.bomtransporte.modelo.ModeloTabela;
import br.com.bomtransporte.modelo.Veiculo;
import br.com.bomtransporte.util.Tela;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author JhonattanSouza_
 */
public class FormMotorista extends javax.swing.JFrame {

    /**
     * Creates new form FormMotorista
     */
    private VeiculoDao veiculoDao;
    private Veiculo veiculoSelecionado;

    public FormMotorista() {
        initComponents();
//        jLB_Nome.setText(FuncionarioSingleton.getFuncionario().getNome());
        preencherTabelaVeiculo();

    }

    private void setarPedidoEntregue(Integer idPedidoCli) throws Exception {
        CargaDao cargaDao = new CargaDao();
        Integer cont = 0;

        List<Object> listaCargas = cargaDao.listarCargas(idPedidoCli);
        for (Object cargaAtual1 : listaCargas) {
            Carga carga = (Carga) cargaAtual1;
            if (!carga.getStatus().equals("Entregue")) {
                cont++;

            }
        }
        if (cont == 0) {
            PedidoDao pedidoDao = new PedidoDao();
            pedidoDao.updateIdPedidoCli(idPedidoCli, "Entregue");
        }
    }

    private  void preencherTabelaVeiculo() {

        ArrayList dados = new ArrayList();
        veiculoDao = new VeiculoDao();
        String[] colunas = new String[]{"ID", "TIPO", "STATUS", "DESTINO"};

        try {
            final List<Object> listaVeiculo = veiculoDao.listar();

            if (listaVeiculo != null && listaVeiculo.size() > 0) {
                for (Object veiculoAtual : listaVeiculo) {
                    Veiculo veiculo = (Veiculo) veiculoAtual;

                    dados.add(new Object[]{veiculo.getIdVeiculo(), veiculo.getTipoVeiculo(), veiculo.getStatus(), veiculo.getDestino()});
                }
            }

            ModeloTabela modTabela = new ModeloTabela(dados, colunas);
            jTB_veiculo.setModel(modTabela);
            jTB_veiculo.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTB_veiculo.getColumnModel().getColumn(0).setResizable(false);
            jTB_veiculo.getColumnModel().getColumn(1).setPreferredWidth(280);
            jTB_veiculo.getColumnModel().getColumn(1).setResizable(false);
            jTB_veiculo.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTB_veiculo.getColumnModel().getColumn(2).setResizable(false);
            jTB_veiculo.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTB_veiculo.getColumnModel().getColumn(3).setResizable(false);

            jTB_veiculo.getTableHeader().setReorderingAllowed(false);
            jTB_veiculo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTB_veiculo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            jTB_veiculo.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        List<Object> lista = veiculoDao.listar();
                        veiculoSelecionado = (Veiculo) lista.
                                get(jTB_veiculo.convertRowIndexToModel(jTB_veiculo.getSelectedRow()));
                        System.err.println(veiculoSelecionado.getIdVeiculo());

                        //     if (veiculoDao.listarVeiculosAtivos().size() > 0 && veiculoDao.listarVeiculosAtivos() != null) {}
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(FormMotorista.this, "Erro genérico1: " + ex.getMessage());
                        ex.printStackTrace(System.err);
                    }
                }

            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro genérico2: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPN_Background = new javax.swing.JPanel();
        jLB_Nome = new javax.swing.JLabel();
        jLB_BemVindo = new javax.swing.JLabel();
        jBT_AlterarStatusVeiculo = new javax.swing.JButton();
        jBT_Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTB_veiculo = new javax.swing.JTable();
        jBT_Logout = new javax.swing.JButton();
        jLB_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPN_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLB_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Nome.setText("NAME_PLACEHOLDER");
        jPN_Background.add(jLB_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 220, 40));

        jLB_BemVindo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_BemVindo.setText("Bem-Vindo(a)");
        jPN_Background.add(jLB_BemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 40));

        jBT_AlterarStatusVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        jBT_AlterarStatusVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_AlterarStatusVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/alterar-icon.png"))); // NOI18N
        jBT_AlterarStatusVeiculo.setText("Check in");
        jBT_AlterarStatusVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_AlterarStatusVeiculoActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_AlterarStatusVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, 80));

        jBT_Sair.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/sair-icon.png"))); // NOI18N
        jBT_Sair.setText("Sair do Sistema");
        jBT_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_SairActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 180, -1));

        jTB_veiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTB_veiculo);

        jPN_Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 700, 230));

        jBT_Logout.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/logout-icon.png"))); // NOI18N
        jBT_Logout.setText("Logout");
        jBT_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBT_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_LogoutActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 130, -1));

        jLB_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/menu-principal-background.png"))); // NOI18N
        jPN_Background.add(jLB_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPN_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBT_SairActionPerformed

    private void jBT_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_LogoutActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_LogoutActionPerformed

    private void jBT_AlterarStatusVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_AlterarStatusVeiculoActionPerformed
        //verifica se o statusPedidoSelecionado e nulo
        if (veiculoSelecionado.getStatus() == null || veiculoSelecionado.getStatus().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao acessar o veiculo!\n O status do veiculo esta em branco.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (veiculoSelecionado.getStatus().equals("Em rota")) {

            int result = JOptionPane.showConfirmDialog(this,
                    "Todas as cargas foram entregues com sucesso?", null, JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                CargaDao cargaDao = new CargaDao();
                final List<Object> listaCarga;
                try {
                    listaCarga = cargaDao.listarCargasDoVeiculo(veiculoSelecionado.getIdVeiculo());

                    if (listaCarga != null && listaCarga.size() > 0) {
                        for (Object cargaAtual : listaCarga) {
                            Carga carga = (Carga) cargaAtual;

                            if (carga.getStatus().equals("Saiu para entrega")) {
                                carga.setStatus("Entregue");

                            }
                            setarPedidoEntregue(carga.getIdPedido_Cli());

                        }

                    }
                    veiculoDao.updateStatus("Aguardando", veiculoSelecionado.getIdVeiculo());

                } catch (Exception ex) {
                    Logger.getLogger(FormMotorista.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                FormVeiculoCargas.idVeiculoSelecionado = veiculoSelecionado.getIdVeiculo();
                FormVeiculoCargas formV = new FormVeiculoCargas();
                formV.setVisible(true);

            }
            return;
        }

        //cria uma list com os status do veiculo
        List<String> optionList = new ArrayList<>();
        optionList.add("Aguardando");
        optionList.add("Em rota");
        optionList.add("desativado");

        //mostra somente as opcoes necessarias de acordo com a regra de negocio
        switch (veiculoSelecionado.getStatus()) {
            case "Aguardando":
                optionList.remove(2);
                optionList.remove(0);

                break;

            case "desativado":
                optionList.remove(2);
                optionList.remove(1);

                return;

        }

        Object[] options = optionList.toArray();

        //pega o status que o usuario selecionou
        Object value = JOptionPane.showInputDialog(this, "Escolha uma das opcoes",
                "Mudar status do pedido", JOptionPane.QUESTION_MESSAGE, null,
                options,
                options[0]);
        int index = optionList.indexOf(value);

        //atualiza o status no banco
        if (optionList.get(index) != null) {
            try {
                veiculoDao.updateStatus(optionList.get(index), veiculoSelecionado.getIdVeiculo());
                preencherTabelaVeiculo();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao atualizar o status no banco: "
                        + ex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBT_AlterarStatusVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_AlterarStatusVeiculo;
    private javax.swing.JButton jBT_Logout;
    private javax.swing.JButton jBT_Sair;
    private javax.swing.JLabel jLB_Background;
    private javax.swing.JLabel jLB_BemVindo;
    private javax.swing.JLabel jLB_Nome;
    private javax.swing.JPanel jPN_Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTB_veiculo;
    // End of variables declaration//GEN-END:variables
}
