package br.com.bomtransporte.formulario;

import br.com.bomtransporte.dao.CidadeDao;
import br.com.bomtransporte.dao.EnderecoDao;
import br.com.bomtransporte.modelo.Cidade;
import br.com.bomtransporte.modelo.Endereco;
import br.com.bomtransporte.util.Tela;
import br.com.bomtransporte.util.Validacao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Carvalho
 */
public class FormCadastrarCep extends javax.swing.JFrame {

    Cidade cidade;
    CidadeDao cidadeDao;

    /**
     * Creates new form FormCadastrarCep
     */
    public FormCadastrarCep() {
        initComponents();
        Tela.desabilitarBotao(jCB_Cidade);
        preencherJcbUF();
    }

    private void preencherJcbUF() {
        cidadeDao = new CidadeDao();
        try {

            List<Object> list = cidadeDao.listarUf();
            for (Object obj : list) {
                cidade = (Cidade) obj;
                jCB_UF.addItem(cidade.getUf());

            }

        } catch (Exception ex) {
            Logger.getLogger(FormCadastrarCep.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void preencherJcbCidade(String uf) {
        cidadeDao = new CidadeDao();
        try {
            List<String> list = cidadeDao.listarCidadePorUF(uf);
            for (String str : list) {

                jCB_Cidade.addItem(str);
            }
            Tela.habilitarBotao(jCB_Cidade);
        } catch (Exception ex) {
            Logger.getLogger(FormCadastrarCep.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean verificarCep() {
        String cep = jTF_Cep.getText();
        EnderecoDao enderecoDao = new EnderecoDao();
        try {
            Endereco endereco = enderecoDao.retornarEndereco(cep);
            return endereco != null;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO INESPERADO, POR FAVOR CONTATE O ADMINISTRADOR DO SISTEMA.\n" + ex.getMessage(), "ERRO INESPERADO.", JOptionPane.INFORMATION_MESSAGE);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLB_Background1 = new javax.swing.JLabel();
        jLB_CEP1 = new javax.swing.JLabel();
        jTF_Cep = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter cep= new javax.swing.text.MaskFormatter("#####-###"); 
            jTF_Cep = new javax.swing.JFormattedTextField(cep); 
        } 
        catch (Exception e){ 
        }
        jTF_Bairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_Logradouro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBT_Salvar = new javax.swing.JButton();
        jCB_UF = new javax.swing.JComboBox();
        jCB_Cidade = new javax.swing.JComboBox();
        jBT_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(512, 258));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLB_Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 150, -1, -1));

        jLB_CEP1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_CEP1.setText("CEP *");
        getContentPane().add(jLB_CEP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jTF_Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CepActionPerformed(evt);
            }
        });
        getContentPane().add(jTF_Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 47, 180, 30));
        getContentPane().add(jTF_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Logradouro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(jTF_Logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 395, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("UF");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, 30, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Cidade");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Bairro");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jBT_Salvar.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Salvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/salvar-icon.png"))); // NOI18N
        jBT_Salvar.setText("Salvar ");
        jBT_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jCB_UF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCB_UF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_UFItemStateChanged(evt);
            }
        });
        getContentPane().add(jCB_UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 88, 72, 40));

        jCB_Cidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        getContentPane().add(jCB_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 280, 40));

        jBT_Voltar.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBT_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/retornar-icon.png"))); // NOI18N
        jBT_Voltar.setText("Voltar");
        jBT_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_CepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CepActionPerformed

    private void jBT_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_SalvarActionPerformed
        List<String> campos = new ArrayList();
        campos.add(jTF_Cep.getText());
        campos.add(jTF_Bairro.getText());
        campos.add(jTF_Logradouro.getText());
        campos.add((String) jCB_Cidade.getSelectedItem());
        campos.add((String) jCB_UF.getSelectedItem());

        if (Validacao.verificarCamposVazios(campos)) {
            if (!verificarCep()) {
                try {
                    Endereco endereco = new Endereco();
                    EnderecoDao enderecoDao = new EnderecoDao();

                    endereco.setCep(campos.get(0));
                    endereco.setBairro(campos.get(1));
                    endereco.setLogradouro(campos.get(2));
                    endereco.setNomeCidade(campos.get(3));
                    endereco.setUf(campos.get(4));

                    enderecoDao.inserir(endereco);
                    this.dispose();

                    JOptionPane.showMessageDialog(this, "CEP INCLUÍDO COM SUCESSO!", "SUCESSO",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    Logger.getLogger(FormCadastrarCep.class.getName()).log(Level.SEVERE, null, e);

                }
            } else {
                JOptionPane.showMessageDialog(this, "ESTE CEP JÁ ESTÁ CADASTRADO NO SISTEMA.!",
                        "CEP JÁ CADASTRADO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "CAMPOS NECESSÁRIOS EM BRANCO.", "CAMPOS EM BRANCO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBT_SalvarActionPerformed

    private void jCB_UFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_UFItemStateChanged
        jCB_Cidade.removeAllItems();
        preencherJcbCidade((String) jCB_UF.getSelectedItem());
    }//GEN-LAST:event_jCB_UFItemStateChanged

    private void jBT_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jBT_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormCadastrarCep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_Salvar;
    private javax.swing.JButton jBT_Voltar;
    private javax.swing.JComboBox jCB_Cidade;
    private javax.swing.JComboBox jCB_UF;
    private javax.swing.JLabel jLB_Background1;
    private javax.swing.JLabel jLB_CEP1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTF_Bairro;
    private javax.swing.JTextField jTF_Cep;
    private javax.swing.JTextField jTF_Logradouro;
    // End of variables declaration//GEN-END:variables
}
