package br.com.bomtransporte.formulario;

import br.com.bomtransporte.modelo.FuncionarioSingleton;
import br.com.bomtransporte.util.Tela;

/**
 *
 * @author JhonattanSouza_
 */
public class FormMotorista extends javax.swing.JFrame {

    /**
     * Creates new form FormMotorista
     */
    public FormMotorista() {
        initComponents();
        jLB_Nome.setText(FuncionarioSingleton.getFuncionario().getNome());
        Tela.adicionarHover(jBT_Senha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPN_Background = new javax.swing.JPanel();
        jLB_Legenda3 = new javax.swing.JLabel();
        jLB_Icon3 = new javax.swing.JLabel();
        jBT_StatusPedido = new javax.swing.JLabel();
        jLB_Legenda2 = new javax.swing.JLabel();
        jLB_Icon2 = new javax.swing.JLabel();
        jBT_Senha = new javax.swing.JLabel();
        jLB_Nome = new javax.swing.JLabel();
        jLB_BemVindo = new javax.swing.JLabel();
        jBT_Sair = new javax.swing.JButton();
        jBT_Logout = new javax.swing.JButton();
        jLB_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPN_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLB_Legenda3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda3.setText("<html>Check-in<br/>Pedidos</html>");
        jLB_Legenda3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 150, 60));

        jLB_Icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/senha-icon.png"))); // NOI18N
        jLB_Icon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 50, 60));

        jBT_StatusPedido.setBackground(new java.awt.Color(0, 0, 0));
        jBT_StatusPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_StatusPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_StatusPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_StatusPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_StatusPedidoMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_StatusPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 150, 150));

        jLB_Legenda2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Legenda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLB_Legenda2.setText("<html>Alterar<br/>Senha</html>");
        jLB_Legenda2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Legenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 150, 60));

        jLB_Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/senha-icon.png"))); // NOI18N
        jLB_Icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPN_Background.add(jLB_Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 50, 60));

        jBT_Senha.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/btn-dashboard2.png"))); // NOI18N
        jBT_Senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBT_Senha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBT_SenhaMouseReleased(evt);
            }
        });
        jPN_Background.add(jBT_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, 150));

        jLB_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_Nome.setText("NAME_PLACEHOLDER");
        jPN_Background.add(jLB_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 220, 40));

        jLB_BemVindo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLB_BemVindo.setText("Bem-Vindo(a)");
        jPN_Background.add(jLB_BemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 40));

        jBT_Sair.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/sair-icon.png"))); // NOI18N
        jBT_Sair.setText("Sair do Sistema");
        jBT_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_SairActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 180, -1));

        jBT_Logout.setBackground(new java.awt.Color(0, 0, 0));
        jBT_Logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBT_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/icones/logout-icon.png"))); // NOI18N
        jBT_Logout.setText("Logout");
        jBT_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBT_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_LogoutActionPerformed(evt);
            }
        });
        jPN_Background.add(jBT_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 130, -1));

        jLB_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bomtransporte/imagem/menu-principal-background.png"))); // NOI18N
        jPN_Background.add(jLB_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPN_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_SenhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_SenhaMouseReleased
        FormAlterarSenha formSenha = new FormAlterarSenha();
        formSenha.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_SenhaMouseReleased

    private void jBT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBT_SairActionPerformed

    private void jBT_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_LogoutActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBT_LogoutActionPerformed

    private void jBT_StatusPedidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_StatusPedidoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_StatusPedidoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_Logout;
    private javax.swing.JButton jBT_Sair;
    private javax.swing.JLabel jBT_Senha;
    private javax.swing.JLabel jBT_StatusPedido;
    private javax.swing.JLabel jLB_Background;
    private javax.swing.JLabel jLB_BemVindo;
    private javax.swing.JLabel jLB_Icon2;
    private javax.swing.JLabel jLB_Icon3;
    private javax.swing.JLabel jLB_Legenda2;
    private javax.swing.JLabel jLB_Legenda3;
    private javax.swing.JLabel jLB_Nome;
    private javax.swing.JPanel jPN_Background;
    // End of variables declaration//GEN-END:variables
}
